# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool: 
  name: default
  demands: agent.name
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'    

# - task: Gitleaks@2
#   inputs:
#     scanlocation: '$(Build.SourcesDirectory)/app.js'
#     configtype: 'predefined'
#     predefinedconfigfile: 'UDMSecretChecksv8.toml'
#     reportformat: 'json'
#     #reportpath: '$(Build.SourcesDirectory)/gitleaks-report.json'
#   displayName: 'GitLeak Scan for app.js'

- script: |
    echo "Running GitLeaks Scan"
    gitleaks detect --config=$(Build.SourcesDirectory)/UDMSecretChecksv8.toml --source=$(Build.SourcesDirectory) --report-format=json --report-path=$(Build.SourcesDirectory)/gitleaks-report.json
    if [ $? -eq 99 ]; then
      echo "Leaks found, but pipeline will continue."
    else
      exit $?
    fi
  displayName: 'GitLeaks Scan for Secrets'
  
- script: |
    echo "Displaying GitLeaks Report:"
    cat $(Build.SourcesDirectory)/gitleaks-report.json
  displayName: 'Display GitLeaks Report in Logs'