trigger:
  - main

pool:
  name: Default
  demands: agent.name -equals agent-pod
  vmImage: 'ubuntu-latest'

stages:
  - stage: Nodejs
    displayName: Set Up NodeJs
    jobs:
      - job:
        steps:
          - task: NodeTool@0
            inputs:
              versionSource: 'spec'
              versionSpec: '16.x'
              checkLatest: true
            displayName: 'Set Up NodeJS'

          - script: npm install
            displayName: 'Install Dependencies'

          - script: npm run build
            displayName: 'Build Project'

  - stage: SonarQube_Analysis
    displayName: Code Quality Test
    jobs:
      - job: 
        steps:
          - task: SonarQubePrepare@7
            inputs:
              SonarQube: 'SonarQube'
              scannerMode: 'cli'
              configMode: 'manual'
              cliProjectKey: 'Practice1_Practice1_54448cfd-937a-4c3c-bd91-7348822ab3e3'
              cliProjectName: 'Pharmacy'
              cliSources: '.'

          - task: SonarQubeAnalyze@7
            inputs:
              jdkversion: 'JAVA_HOME_17_X64'

          - task: SonarQubePublish@7
            inputs:
              pollingTimeoutSec: '300'